### ISSUE TITLE
Middleware/Services

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/API#14]
This is just going to be a curated list of features that we want added to the API for handling global requests, and maybe a little dreaming...
1. Logging mechanism
   - Aggregating all levels of log info (DEBUG,INFO,WARNING,ERROR)
   - This would essentially be an interface that inherits the properties from log.Logger*
2. TimeSince Metrics
   - Will calculate and log the amount of time requests are spending in different functions
   - Could maybe be rolled into the Logging Mechanism
3. Analytics Service
   - We've currently integrated with Segment.io, but once we got into the cost of this, it'd be nice to aggregate these metrics into something a little more scalable for us, Cassandra, Redis, Logstash, etc.
4. Rate Limiting
   - We will probably never strongly enforce the limit of requests that a key can make, but we may want to have this logic in place from the beginning so we can turn it on if the need arises.

I'll add more as I think of them, if you have ideas, please add them to this list or in the comments.

**Comment by ninnemana** [comment]
So, what do we think of the middleware approach? Should I spend the time converting everything?

**Comment by DavidVaini** [comment]
I say go for it, it seems to have simplified a lot of things and cleans up some code. A little more lengthy on getting params and the sorts, but I like how you can define a "keyed" route.

**Comment by ninnemana** [comment]
You mean `ctx.Params.ByName("id")` instead of the old `params["id"]`?

**Comment by DavidVaini** [comment]
yeah thats just one of the things, that and form data, I know it seems silly cause its only 10 more characters, but it being an API its one of the primary things you do (take in data). I know I am just nitpicking because the new middleware seems to be that good, just pointing out things I noticed :)

**Comment by stinkyfingers** [comment]
I like it.
