### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/API#47]
Dun dun dun....

We knew it was going to have to be done at some point right?

**Comment by DavidVaini** [comment]
noooooooooooooooooo

yeah, I figured this was coming.

**Comment by DavidVaini** [comment]
So I think the general consensus for this project is to have it done in some automated GoDoc way.

**Comment by DavidVaini** [comment]
This might help:
http://blog.golang.org/godoc-documenting-go-code

**Comment by DavidVaini** [comment]
So I can get the godoc tool to work on individual files, but using the typical browser way, both John and I get a "Webpage cannot be found" error, even though the command seems to work successfully. I am still looking into this.

Most of our API doesnt have any of the comments, so the documentation that is generated is pretty basic and just shows basic function names, this will have to be updated over time.

**Comment by DavidVaini** [comment]
He said he would take care of it and Alex confirmed he can do it.

**Comment by stinkyfingers** [comment]
When is this going to be done? I have some customers that want good, thorough documentation right now.

**Comment by baseigneurie** [comment]
:hadoop:

**Comment by mickelsonm** [comment]
That's a very good question @stinkyfingers . Observe the history of this issue... @DavidVaini sure is eager to keep handing it off. I am surprised a CURT 2014 Peak Performer didn't self-assign this... @ninnemana better note this in the upcoming performance review :wink:

**Comment by DavidVaini** [comment]
I didnt hand it off, he volunteered, we were all here lol

**Comment by mickelsonm** [comment]
The 2015 Peak Performer award is looking like a win for @stinkyfingers ... better step up your game @DavidVaini :wink:

**Comment by DavidVaini** [comment]
@mickelsonm I just gotta really "give her" for like 3 hours one day. On a serious note, if he gets it, I will be proud of him. He has been doing a great job!

**Comment by mickelsonm** [comment]
@DavidVaini "give her"...like give her a :cookie:? lol. It has been fun watching you guys at work. I think you all should be proud of what you're doing, even when you don't always know what it is you're supposed to be working on or you don't get praise/encouragement for the things you've done. Anyways, great work guys and keep it Go-ing!!!

**Comment by ninnemana** [comment]
Can we get the homepage README updated too? The tech list is definitely out of date.
