### ISSUE TITLE
Sub Categories Endpoint?

### ISSUE THREAD

**Issue by jnbn** [curt-labs/API#60]
There was an endpoint named /category/{id}/subs but seems like broken or removed?

Can you please check and inform about it?

Because it's still on documentation as
```
GET - http://API.curtmfg.com/category/<parent category id>/subs?key=[public api key]
```

**Comment by ninnemana** [comment]
I believe the `/subs` endpoint was removed when we incorporated everything into the requested categories response. So calling the following endpoint returns the requested category and the entire category hierarchy of sub-categories.

```
GET - http://API.curtmfg.com/category/<parent category id>?key=[public api key]
```

We could consider adding back the explicit `/subs` endpoint, but in my opinion the only benefit would be the lower cost of network latency for the extra data.
