### ISSUE TITLE
All Collection Lookup Performance

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/API#61]
```shell
boom -c 10 -n 100 -m POST -d 'year=2013&make=chevrolet&model=silverado+1500&style=&collection=' http://goapi.curtmfg.com/vehicle/mongo/allCollections?key=[some key]
```
<img src="https://cloud.githubusercontent.com/assets/187030/12336128/4c11cd9c-bac8-11e5-98bc-159d29a16380.png" width="700" height="650">

**Comment by DavidVaini** [comment]
good news and bad news, I updated all my mongo collections to be an exact copy of the live MongoDB,  Then ran it locally, here are my results:
![screen shot 2016-01-14 at 3 06 51 pm](https://cloud.githubusercontent.com/assets/2159280/12337584/7dd1de46-bad0-11e5-824f-9497d974c77d.png)

**Comment by DavidVaini** [comment]
My guess is its opening a bunch of connections and thats why its slow on the server but not locally

**Comment by DavidVaini** [comment]
https://github.com/curt-labs/API/commit/8521389f14f7d7d917daaf2d6e8350eb60e70f6e

I guess we will see..

**Comment by DavidVaini** [comment]
![screen shot 2016-01-14 at 3 58 16 pm](https://cloud.githubusercontent.com/assets/2159280/12338903/d0fc1bca-bad7-11e5-80aa-f25aaa3ab246.png)

Looks like its faster, but still could use room for improvement

**Comment by ninnemana** [comment]
e297287b039c9bcaa56897a27ed68ebd7a652d9d
