### ISSUE TITLE
How to obtain an API key?

### ISSUE THREAD

**Issue by maxaud** [curt-labs/API#62]
Who would I talk to about getting an API key? Should I just continue using the V2 API instead?

**Comment by ninnemana** [comment]
API keys are distributed through our [Dealer Portal](http://dealers.curtmfg.com). If you have an account you can view your API keys under `Account Settings`, otherwise you will have to create an account.

**Comment by maxaud** [comment]
Got it taken care of, thank you, Alex.

**Comment by ninnemana** [comment]
Good to hear.
