### ISSUE TITLE
Customer Integration Missing

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/API#63]
When retrieving product data, there is a `Customer` section of the `Part` object that should contain custom pricing, and cross-site reference. This doesn't appear to be functional.

[master](http://api.curtmfg.com/v3/part/13118?key=YOUR+API+KEY+HERE)
[goapi](http://goapi.curtmfg.com/part/13118?key=YOUR+API+KEY+HERE)

**Comment by stinkyfingers** [comment]
Sounds like we need a different way to achieve this.

**Comment by stinkyfingers** [comment]
1d453d1906ce7ba22839f88000d974870ebb3454
