### ISSUE TITLE
Paging issue on all parts end point.

### ISSUE THREAD

**Issue by joelthecoder** [curt-labs/API#64]
I'm writing a script to pull all the parts to sync with a Shopify catalog and I'm running into an issue where every page after the 1st page returns this error:

```
http://api.curtmfg.com/v3/part?key=xxxxxx&page=2&count=500
```

```
{"message":"Trouble getting all parts","messageDetails":"Executor error during find command: OperationFailed: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit.","request_body":"","query_string":{"count":["500"],"key":["xxxxxxx"],"page":["2"]}}
```

I was using

```
http://api.curtmfg.com/v2/GetAllParts?dataType=JSON
```

but started getting a 504 time out

**Comment by baseigneurie** [comment]
For now, you can temporarily lower your count to 450. We're looking into fixing the memory issue now.

**Comment by ninnemana** [comment]
Is this a MongoDB query or are we pulling this data from MySQL?

**Comment by baseigneurie** [comment]
This is querying MongoDB

**Comment by ninnemana** [comment]
Seems to have a sort on `id`. Is this the correct field for us to sort on? If so, we should index this field. If not, what field should we sort on and can we index that field?

**Comment by ninnemana** [comment]
Agree 🍻

**Comment by baseigneurie** [comment]
You should now be able to use this query with a count of 500 again.

I have removed duplicates from mongo and implemented the index. I have also added code to ensure the index persists. Closing the issue.
https://github.com/curt-labs/API/commit/63e34aafa74b3c289eaccfcd770bd6c31759efc4

**Comment by joelthecoder** [comment]
Thank you for resolving! 👍
