### ISSUE TITLE
Filter return values on all parts endpoint

### ISSUE THREAD

**Issue by joelthecoder** [curt-labs/API#65]
I'm wondering if adding the ability to specify which columns to either exclude or include would be a good idea to reduce the size of the response.

Each part seems to have a `categories` node which sometimes has `part_ids` that can be a very long list. Is this something you guys have considered?

**Comment by ninnemana** [comment]
@joelthecoder how would you like to see this implemented? Would you like to `POST` a payload the matched the queried objects schema? Ex:

```json
{
	"part_number": true,
	"status": true,
	"average_review": true,
	"date_modified": true,
	"date_added": true,
	"short_description": true,
	"install_sheet": {
		"Scheme": true,
		"Host": true,
		"Path": true,
	},
	"attributes": [{
		"name": true,
		"value": true
	}]
}
```
or

Would you prefer to post a requested field array? Ex:

```json
["part_number", "status", "average_review", "short_description", "attributes"]
```

The difficult part with the later is handling nested properties. Say you only want the text of a piece a content, but not the associated metadata. How does one communicated that requirement in a field list? My initial inclination is to use a name spacing approach ex: `["content:text": true, "content:contentType": false]`.

Lots of thinking out loud there, but I'm curious on your preference. It really helps to hear a use-case to apply the logic to.

**Comment by ninnemana** [comment]
Downside of posting the payload would be that it turns all part calls into `POST` requests.

**Comment by joelthecoder** [comment]
I wouldn't worry about nested objects. You should have an endpoint to fetch those individually as required.

For instance:

```
GET
http://api.curtmfg.com/v3/part?fields=part_number,date_modified
```

If I don't include the attributes field but later find need to fetch -- I can fetch by..

```
GET
http://api.curtmfg.com/v3/part/{id}/attributes
```
