### ISSUE TITLE
Data Change Feed

### ISSUE THREAD

**Issue by ninnemana** [curt-labs/API#66]
Throwing an idea into the wild....

Wouldn't it be cool if we aggregated change history inside of PubSub to distribute real time data change information?

We could put the aggregated data into InfluxDB or maybe even Mongo and then stream it out through the API for consumption.

**Comment by ngamer** [comment]
As a consumer of this data, what does this mean to me if I am a customer? Can you phrase this into laymen terms.

Thanks,

Noah
